#!/bin/csh
#
#
#SBATCH --partition=gpu4090
#SBATCH --qos=4gpus
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --gpus=1
#SBATCH -o job.%j.err
#SBATCH -e job.%j.out
# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

# This folder contains GROMACS formatted force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommand following command:
# mpirun -np $NUM_CPU gmx mdrun -ntomp 1

set init = step5_input
set rest_prefix = step5_input
set mini_prefix = step6.0_minimization
set mini_step = step6.0
set equi_prefix = step7_equilibration
set equi_step = step7
set prod_prefix = step8_production
set prod_step   = step8

ml gromacs/2023.2-gcc-9.5.0-jzxesel
# Minimization -> step6
# In the case that there is a problem during minimization using a single precision of GROMACS, please try to use 
# a double precision of GROMACS only for the minimization step.
gmx_mpi grompp -f ${mini_prefix}.mdp -o ${mini_step}.tpr -c ${init}.gro -r ${rest_prefix}.gro -p topol.top -n index.ndx
gmx_mpi mdrun -v -deffnm ${mini_step}

#Equilibration -> step7
gmx_mpi grompp -f ${equi_prefix}.mdp -o ${equi_step}.tpr -c ${mini_step}.gro -r ${mini_step}.gro -p topol.top -n index.ndx
gmx_mpi mdrun -v -deffnm ${equi_step}

#Production -> step8
gmx_mpi grompp -f ${prod_prefix}.mdp -o ${prod_step}.tpr -c ${equi_step}.gro -p topol.top -n index.ndx
gmx_mpi mdrun -v -deffnm ${prod_step}




